import { Document, Types } from "mongoose";

export interface IUser {
  auth0Id: string; // Auth0 ID
  userId: string; // User ID (generated by uuid)
  email?: string;
  name?: string;
  picture?: string;
  roles: string[];
  createdAt?: string | Date;
  updatedAt?: string | Date;
  activeTrips: string[];
  pastTrips: string[];
  pendingInvites: string[];
  organizationId?: string | null;
}

export interface IUserDocument extends IUser, Document {
  _id: Types.ObjectId; // mongoose id
}
